[build]
  publish = "public" # Diretório para arquivos estáticos (se aplicável)
  command = "npm run build"
  functions = "functions"  # Localização das funções serverless


[build.environment]
  NODE_VERSION = "20.5.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

